spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@cluster0.knicbgf.mongodb.net/RecHub?retryWrites=true&w=majority&appName=Cluster0&ssl=true

rawg:
  apiKey:
    ${RAWG_API_KEY}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}